blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.rs/b58uuid
    about: View the package documentation on docs.rs
  - name: Discussions
    url: https://github.com/b58uuid/b58uuid-rs/discussions
    about: Ask questions and discuss ideas with the community
